apiVersion: ecs.aws.upbound.io/v1beta1
kind: TaskSet
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1beta1/taskset
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    clusterSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    loadBalancer:
    - containerName: mongo
      containerPort: 8080
      targetGroupArnSelector:
        matchLabels:
          testing.upbound.io/example-name: example
    region: us-west-1
    serviceSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    taskDefinitionSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

